export const GET_REPOS = 'REPOS/GET_REPOS';
export const GET_REPOS_SUCCESS = 'REPOS/GET_REPOS_SUCCESS';
export const GET_REPOS_FAILURE = 'REPOS/GET_REPOS_FAILURE';

export default {
  GET_REPOS,
  GET_REPOS_SUCCESS,
  GET_REPOS_FAILURE,
};